Template API update
yetanalytics/project-persephone pull request #33
Opened 2021-12-15 16:20 UTC by kelvinqian00

TODO: Write updates

2021-12-15 18:35 UTC, FeLungs reviewed
looks clean / easy to use

2021-12-16 13:38 UTC, milt commented
Are there doc updates for this? Would make it easier to adapt stuff like xapipe if the API has breaking changes.

2021-12-16 14:38 UTC, kelvinqian00 commented
Sorry; that was a copy-paste fail.

2021-12-16 14:38 UTC, milt commented on README.md
> +- `:short-circuit?` - If `false` (default), returns error data for all invalid Templates; if `true`, returns data for only the first invalid Template found. Applicable to `:result`, `:assertion`, and
These are really useful, and thoughtful to provide. The combination of the two gives lib consumers a lot of flexibility

2021-12-20 18:49 UTC, milt commented
> Remove JSON string parsing (note: affects Pattern API also)

OK, how does a lib consumer deserialize a profile now? Just vanilla JSON parse?

2021-12-20 18:51 UTC, kelvinqian00 commented
> OK, how does a lib consumer deserialize a profile now? Just vanilla JSON parse?

As per your recommendations, they would need to have the Statements and Profiles parsed into EDN _before_ passing them into the API. They would do regular JSON parsing, just keywording keys for Profiles and stringifying keys for Statements.

2021-12-20 18:53 UTC, milt commented
> As per your recommendations, they would need to have the Statements and Profiles parsed into EDN before passing them into the API. They would do regular JSON parsing, just keywording keys for Profiles and stringifying keys for Statements.

That sounds good. `#(keyword nil %)` works for all cases, right? Like there's no part of profiles with IRI keys?

2021-12-20 18:54 UTC, kelvinqian00 commented
> That sounds good. #(keyword nil %) works for all cases, right? Like there's no part of profiles with IRI keys?

No (at least not in the spec, though I guess the user can add extraneous IRI keys, but then that's their problem). The main troublesome key would be `@context`, but that gets ignored by Persephone post-validation so they could just convert it to `:_context`.

2021-12-20 18:56 UTC, milt commented
> ...so they could just convert it to `:_context`

So you're saying the lib consumer _will_ have to do special key coercion then, right?

2021-12-20 18:58 UTC, kelvinqian00 commented
> So you're saying the lib consumer will have to do special key coercion then, right?

Erm yes, but that's more of a Pan problem than a Persephone problem. But I see your point - maybe add back the `coerce-profile` and `coerce-statement` functions as functions the user can call?

2021-12-20 18:59 UTC, milt commented
> ...maybe add back...

Yeah that sounds like a good balance, so you don't have to force a parsing choice but folks can have guarantees about structure

2021-12-20 22:07 UTC, milt requested changes
~~Looks like there are some additional spec/instrumentation issues that come up when using the new API for direct template compilation. See concept filter test fails on https://github.com/yetanalytics/xapipe/pull/68.~~

It appears there is actually a bug in DATASIM or xapipe's test profile that is yielding invalid statements, it doesn't look like persephone.

2021-12-21 15:18 UTC, milt approved these changes
OK, all the downstream issues are outside of persephone's purview, this is looking really good.

2021-12-21 20:03 UTC, cliffcaseyyet approved these changes

2021-12-21 20:15 UTC, merged